spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.80.138:3306/weiyunmall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #注册中心的地址
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.80.138
    port: 6379
  cache:
    type: redis #缓存类型
    redis:
      time-to-live: 60000
      cache-null-values: true #防止缓存穿透
#    alicloud:
#      access-key: *****
#      secret-key: *****
#      oss:
#        endpoint: ******
#        bucket-name: weiyunmall
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #主键自增
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10000
logging:
  level:
    com.taotao.weiyunmall: error
include-binding-errors: always
include-message: always
