spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: 保密
      secret-key: 保密
      oss:
        endpoint: *******
        bucket: weiyunmall
  application:
    name: weiyunmall-third-party
server:
  port: 30000
