spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI5t5qdN2hrzbroFsgfx2z
      secret-key: bZ1hkj81baB3eVfhWn7zvd4EKbDV1t
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: weiyunmall
  application:
    name: weiyunmall-third-party
server:
  port: 30000